// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.ObjCRuntime;

namespace theVault
{
	public partial class CredentialsViewController : UITableViewController
	{	
		public override string Title {
			get {
				return NSBundle.MainBundle.LocalizedString ("Credentials", "Credentials");;
			}
		}
		
		static bool UserInterfaceIdiomIsPhone {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
		}

		public CredentialsViewController (IntPtr handle) : base (handle)
		{
			//∫this.Title = NSBundle.MainBundle.LocalizedString ("Credentials", "Credentials");
			this.TabBarItem.Image = UIImage.FromBundle ("Images/first");		
		}
		
		public override void DidReceiveMemoryWarning ()
		{
			// Releases the view if it doesn't have a superview.
			base.DidReceiveMemoryWarning ();
			
			// Release any cached data, images, etc that aren't in use.
		}
		
		#region View lifecycle
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
					
			this.TableView.Delegate = new CredentialsViewDelegate();
			this.TableView.DataSource = new CredentialsViewDataSource();
		}
		
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();

			this.TableView.Delegate.Dispose();
			this.TableView.Delegate = null;
			
			this.TableView.DataSource.Dispose();
			this.TableView.DataSource = null;
						
			ReleaseDesignerOutlets ();
		}
		
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
		}
		
		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
		}
		
		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);
		}
		
		public override void ViewDidDisappear (bool animated)
		{
			base.ViewDidDisappear (animated);
		}
		
		#endregion
				
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{		
			return true;
		}
	}
}
