// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace theVault
{
	public partial class MainViewController : UIViewController
	{
		private CredentialsViewController _credentialsView;
		private NotesViewController _notesView;
		
		public MainViewController (IntPtr handle) : base (handle)
		{
		}
		
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
				
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_credentialsView = new CredentialsViewController();
			_notesView = new NotesViewController();
						
			_tabBar.AddViewController(_credentialsView);
			_tabBar.AddViewController(_notesView);
			_tabBar.SetParentViewController(this);
			_tabBar.SelectView(_credentialsView);
		}
	}
}
