// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace theVault
{
	public partial class MainViewController : UIViewController
	{
		private CredentialsViewController _credentialsView;
		private SecondViewController _secondView;
		private UIButton button;
		
		public MainViewController (IntPtr handle) : base (handle)
		{
		}
		
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
				
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_credentialsView = new CredentialsViewController(this.Handle);		
			_secondView = new SecondViewController(this.Handle);
						
			_tabBar.AddViewController(_credentialsView);
			_tabBar.AddViewController(_secondView);
			_tabBar.SetParentViewController(this);
			//_tabBar.SelectView(_credentialsView);
		}
	}
}
